host = "0.0.0.0"
port = 6001
debug = false

[app_manager]
driver = "pgsql"

[adapter]
driver = "redis"

[cache]
driver = "redis"

[queue]
driver = "redis"

[rate_limiter]
enabled = true
driver = "redis"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9601

[metrics.tcp_exporter]
enabled = false
host = "127.0.0.1"
port = 5000
buffer_size = 1024
